version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: docker-rsi
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: acara-rsi
    ports:
    # Catatan Port: 
      # 5433 (Kiri) = Port di laptop/host yang bebas diganti agar tidak bentrok
      # 5432 (Kanan) = Port bawaan di dalam container PostgreSQL
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: